version: '2'

volumes:
  datamongo: {}

services:
  nginx:
    image: nginx:1.21.1-alpine
    container_name: ai_notebook_nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/nginx/certificates
      - ./app-notebook:/www/data
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    depends_on:
      - ai-notebook-core
      - am-management
      - am-gateway
      - am-webui

  ai-notebook-core:
    image: ai-notebook-core:latest
    container_name: ai_notebook_core
    build:
      context: ./core
      dockerfile: ai-notebook-core.dockerfile
    stdin_open: true
    ports:
      - 8102:8102

  # Gravitee AM containers used to handle authentication.
  am-mongodb:
    image: mongo:4.2
    container_name: gio_am_mongodb
    restart: always
    volumes:
      - datamongo:/data/db
      - ./logs/am-mongodb:/var/log/mongodb

  am-gateway:
    image: graviteeio/am-gateway:${GIO_AM_VERSION}
    container_name: gio_am_gateway
    restart: always
    links:
      - am-mongodb
    depends_on:
      - am-mongodb
    volumes:
      - ./logs/am-gateway:/etc/gravitee.io/log
    environment:
      - gravitee_management_mongodb_uri=mongodb://am-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://am-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000

  am-management:
    image: graviteeio/am-management-api:${GIO_AM_VERSION}
    container_name: gio_am_management
    restart: always
    links:
      - am-mongodb
    depends_on:
      - am-mongodb
    volumes:
      - ./logs/am-management-api:/etc/gravitee.io/log
    environment:
      - gravitee_management_mongodb_uri=mongodb://am-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://am-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000

  am-webui:
    image: graviteeio/am-management-ui:${GIO_AM_VERSION}
    container_name: gio_am_webui
    restart: always
    depends_on:
      - am-management
    environment:
      - MGMT_API_URL=https://altheadev.net/am
      - MGMT_UI_URL=https://altheadev.net/am/ui
    volumes:
      - ./logs/am-webui:/var/log/httpd
